 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/receivables", type: :request do
  
  # Receivable. As you add validations to Receivable, be sure to
  # adjust the attributes here as well.
  let(:user){ FactoryBot.create(:user, email: 'diego@example.com') }
  let(:valid_attributes) {
    FactoryBot.attributes_for(:receivable).merge!(user_id: user.id)
  }


  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    before { sign_in user }

    context "when Receivable is present" do
      it "renders a successful response" do
        Receivable.create! valid_attributes
        get receivables_url
        expect(response).to be_successful
      end
    end

    context "when Receivable is empty" do
      it "renders a successful response" do
        get receivables_url
        expect(response).to be_successful
      end
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      receivable = Receivable.create! valid_attributes
      get receivable_url(receivable)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_receivable_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      receivable = Receivable.create! valid_attributes
      get edit_receivable_url(receivable)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Receivable" do
        expect {
          post receivables_url, params: { receivable: valid_attributes }
        }.to change(Receivable, :count).by(1)
      end

      it "redirects to the created receivable" do
        post receivables_url, params: { receivable: valid_attributes }
        expect(response).to redirect_to(receivable_url(Receivable.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Receivable" do
        expect {
          post receivables_url, params: { receivable: invalid_attributes }
        }.to change(Receivable, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post receivables_url, params: { receivable: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested receivable" do
        receivable = Receivable.create! valid_attributes
        patch receivable_url(receivable), params: { receivable: new_attributes }
        receivable.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the receivable" do
        receivable = Receivable.create! valid_attributes
        patch receivable_url(receivable), params: { receivable: new_attributes }
        receivable.reload
        expect(response).to redirect_to(receivable_url(receivable))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        receivable = Receivable.create! valid_attributes
        patch receivable_url(receivable), params: { receivable: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested receivable" do
      receivable = Receivable.create! valid_attributes
      expect {
        delete receivable_url(receivable)
      }.to change(Receivable, :count).by(-1)
    end

    it "redirects to the receivables list" do
      receivable = Receivable.create! valid_attributes
      delete receivable_url(receivable)
      expect(response).to redirect_to(receivables_url)
    end
  end
end
