 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/save_money_wallets", type: :request do
  
  # SaveMoneyWallet. As you add validations to SaveMoneyWallet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SaveMoneyWallet.create! valid_attributes
      get save_money_wallets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      save_money_wallet = SaveMoneyWallet.create! valid_attributes
      get save_money_wallet_url(save_money_wallet)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_save_money_wallet_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      save_money_wallet = SaveMoneyWallet.create! valid_attributes
      get edit_save_money_wallet_url(save_money_wallet)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SaveMoneyWallet" do
        expect {
          post save_money_wallets_url, params: { save_money_wallet: valid_attributes }
        }.to change(SaveMoneyWallet, :count).by(1)
      end

      it "redirects to the created save_money_wallet" do
        post save_money_wallets_url, params: { save_money_wallet: valid_attributes }
        expect(response).to redirect_to(save_money_wallet_url(SaveMoneyWallet.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SaveMoneyWallet" do
        expect {
          post save_money_wallets_url, params: { save_money_wallet: invalid_attributes }
        }.to change(SaveMoneyWallet, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post save_money_wallets_url, params: { save_money_wallet: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested save_money_wallet" do
        save_money_wallet = SaveMoneyWallet.create! valid_attributes
        patch save_money_wallet_url(save_money_wallet), params: { save_money_wallet: new_attributes }
        save_money_wallet.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the save_money_wallet" do
        save_money_wallet = SaveMoneyWallet.create! valid_attributes
        patch save_money_wallet_url(save_money_wallet), params: { save_money_wallet: new_attributes }
        save_money_wallet.reload
        expect(response).to redirect_to(save_money_wallet_url(save_money_wallet))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        save_money_wallet = SaveMoneyWallet.create! valid_attributes
        patch save_money_wallet_url(save_money_wallet), params: { save_money_wallet: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested save_money_wallet" do
      save_money_wallet = SaveMoneyWallet.create! valid_attributes
      expect {
        delete save_money_wallet_url(save_money_wallet)
      }.to change(SaveMoneyWallet, :count).by(-1)
    end

    it "redirects to the save_money_wallets list" do
      save_money_wallet = SaveMoneyWallet.create! valid_attributes
      delete save_money_wallet_url(save_money_wallet)
      expect(response).to redirect_to(save_money_wallets_url)
    end
  end
end
